{
  "config": {
    "error": {
      "cannot_connect": "[%key:common::config_flow::error::cannot_connect%]",
      "connection_exists": "Plugwise USB-Stick already configured",
      "network_down": "Plugwise Zigbee network is down",
      "network_timeout": "Network communication timeout",
      "stick_init": "Initialization of Plugwise USB-stick failed",
      "unknown": "[%key:common::config_flow::error::unknown%]"
    },
    "step": {
      "user": {
        "description": "Setup direct connection to legacy Plugwise USB-stick",
        "data": {
          "usb_path": "[%key:common::config_flow::data::usb_path%]"
        }
      },
      "manual_path": {
        "data": {
          "usb_path": "[%key:common::config_flow::data::usb_path%]"
        }
      }
    }
  }
}